version: '3.8'

services:
  redis:
    image: redis/redis-stack-server:latest
    container_name: redis-stack
    restart: always
    ports:
      - "6379:6379"

  postgres:
    image: postgres:16
    restart: always
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=dev

  # simple web-based database admin panel
  adminer:
    image: adminer:4.8.1-standalone
    restart: always
    ports:
      - 8080:8080
    environment:
      - ADMINER_DEFAULT_SERVER=postgres

volumes:
  pgdata:
